### ISSUE TITLE
Maven deploy URL from README is broken.

### ISSUE THREAD

**Issue by preston** [OSEHRA/ISAAC#1]
The URL called out in the README does not appear to resolve correctly:

  http://vadev.mantech.com:8081/nexus/content/repositories/snapshots

The README in general could use a lot of love.

**Comment by kec** [comment]
Info on the deploy URL has been changed. Deployment should use the altDeploymentRepository property defined in a users settings.xml file. 

In addition, lots of new stuff have been pushed, and there will be more active development on this source base going forward. 

There will be "lots of love" added here, and to the KOMET documentation, they will evolve in parallel.
